name: test

on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        description: Tipo de Release
        options: 
        - test

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.triggering_actor }} == ${{secrets.PROJECT_OWNER }}
    steps:
    - name: echo triggering
      run: echo ${{ github.triggering_actor }}
    - name: echo owner
      run: echo ${{ github.repository_owner }}
