name: Scorched-CI-Release
on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        description: Release Type
        options: 
        - major
        - minor
        - patch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read Docker Image Identifiers
        run: echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: test
        run: echo ${{ env.IMAGE_REPOSITORY }}
