name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        description: Tipo de Release
        options: 
        - major
        - minor
        - patch


jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    if: github.ref == 'refs/heads/develop'
    steps:
    - name: Scorched-CI-Release
      uses: ScorchedDevs/scorched-ci@v1-4-0
      env:
        REPO_NAME: ${{ github.repository }}
        TOKEN: ${{ secrets.TOKEN }}
